# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_radon.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 600)
        MainWindow.setMaximumSize(QtCore.QSize(988, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBorrar.setGeometry(QtCore.QRect(170, 180, 75, 23))
        self.pushButtonBorrar.setObjectName("pushButtonBorrar")
        self.pushButtonAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAgregar.setGeometry(QtCore.QRect(80, 180, 75, 23))
        self.pushButtonAgregar.setObjectName("pushButtonAgregar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 220, 51, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 280, 51, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 280, 51, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 220, 51, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 250, 61, 20))
        self.label_6.setObjectName("label_6")
        self.textEditParametersChart = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditParametersChart.setGeometry(QtCore.QRect(20, 10, 281, 141))
        self.textEditParametersChart.setObjectName("textEditParametersChart")
        self.lineEditIntensidad = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditIntensidad.setGeometry(QtCore.QRect(80, 220, 81, 20))
        self.lineEditIntensidad.setObjectName("lineEditIntensidad")
        self.lineEditSemiEjeX = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSemiEjeX.setGeometry(QtCore.QRect(80, 250, 81, 20))
        self.lineEditSemiEjeX.setObjectName("lineEditSemiEjeX")
        self.lineEditCentroX = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCentroX.setGeometry(QtCore.QRect(80, 280, 81, 20))
        self.lineEditCentroX.setObjectName("lineEditCentroX")
        self.lineEditInclinacion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInclinacion.setGeometry(QtCore.QRect(260, 220, 81, 20))
        self.lineEditInclinacion.setObjectName("lineEditInclinacion")
        self.lineEditSemiEjeY = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSemiEjeY.setGeometry(QtCore.QRect(260, 250, 81, 20))
        self.lineEditSemiEjeY.setObjectName("lineEditSemiEjeY")
        self.lineEditCentroY = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCentroY.setGeometry(QtCore.QRect(260, 280, 81, 20))
        self.lineEditCentroY.setObjectName("lineEditCentroY")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 22))
        self.menubar.setObjectName("menubar")
        self.menuGuiRadon = QtWidgets.QMenu(self.menubar)
        self.menuGuiRadon.setObjectName("menuGuiRadon")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuGuiRadon.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonBorrar.setText(_translate("MainWindow", "Borrar"))
        self.pushButtonAgregar.setText(_translate("MainWindow", "Agregar"))
        self.label.setText(_translate("MainWindow", "Intensidad"))
        self.label_2.setText(_translate("MainWindow", "Semi-eje x"))
        self.label_3.setText(_translate("MainWindow", "Centro x"))
        self.label_4.setText(_translate("MainWindow", "Centro y"))
        self.label_5.setText(_translate("MainWindow", "Inclinacion"))
        self.label_6.setText(_translate("MainWindow", "Semi-eje y"))
        self.menuGuiRadon.setTitle(_translate("MainWindow", "GuiRadon"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
